### ISSUE TITLE
Generar un archivo .txt

### ISSUE THREAD

**Issue by Barthes-bski** [Informatico29/heavy-CRUD#1]
Generar un archivo .txt con tu nombre, sea en contenido o como el nombre del propio archivo.

**Comment by Informatico29** [comment]
hola matias quieres que lo suba a mi proyecto en git. cierto???

**Comment by Barthes-bski** [comment]
Exactamente! No interferirá en nada dentro del proyecto, así que tranquilo.

**Comment by Informatico29** [comment]
bueno cree un jose contreras.txt en mi proyecto..no se si lo puedes ver. o
al menos eso entendi ?
